//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace MovieMakerHelper {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class BoundProperties {
        
        private BoundPropertiesBoundPropertyBool[] boundPropertyBoolField;
        
        private BoundPropertiesBoundPropertyFloatSet[] boundPropertyFloatSetField;
        
        private BoundPropertiesBoundPropertyStringSet[] boundPropertyStringSetField;
        
        private BoundPropertiesBoundPropertyFloat[] boundPropertyFloatField;
        
        private BoundPropertiesBoundPropertyInt[] boundPropertyIntField;
        
        private BoundPropertiesBoundPropertyString[] boundPropertyStringField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BoundPropertyBool", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BoundPropertiesBoundPropertyBool[] BoundPropertyBool {
            get {
                return this.boundPropertyBoolField;
            }
            set {
                this.boundPropertyBoolField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BoundPropertyFloatSet", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BoundPropertiesBoundPropertyFloatSet[] BoundPropertyFloatSet {
            get {
                return this.boundPropertyFloatSetField;
            }
            set {
                this.boundPropertyFloatSetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BoundPropertyStringSet", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BoundPropertiesBoundPropertyStringSet[] BoundPropertyStringSet {
            get {
                return this.boundPropertyStringSetField;
            }
            set {
                this.boundPropertyStringSetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BoundPropertyFloat", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BoundPropertiesBoundPropertyFloat[] BoundPropertyFloat {
            get {
                return this.boundPropertyFloatField;
            }
            set {
                this.boundPropertyFloatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BoundPropertyInt", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BoundPropertiesBoundPropertyInt[] BoundPropertyInt {
            get {
                return this.boundPropertyIntField;
            }
            set {
                this.boundPropertyIntField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BoundPropertyString", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BoundPropertiesBoundPropertyString[] BoundPropertyString {
            get {
                return this.boundPropertyStringField;
            }
            set {
                this.boundPropertyStringField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class BoundPropertiesBoundPropertyBool {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class BoundPropertiesBoundPropertyFloatSet {
        
        private BoundPropertiesBoundPropertyFloatSetBoundPropertyFloatElement[] boundPropertyFloatElementField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BoundPropertyFloatElement", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BoundPropertiesBoundPropertyFloatSetBoundPropertyFloatElement[] BoundPropertyFloatElement {
            get {
                return this.boundPropertyFloatElementField;
            }
            set {
                this.boundPropertyFloatElementField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class BoundPropertiesBoundPropertyFloatSetBoundPropertyFloatElement {
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class BoundPropertiesBoundPropertyStringSet {
        
        private BoundPropertiesBoundPropertyStringSetBoundPropertyStringElement[] boundPropertyStringElementField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BoundPropertyStringElement", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BoundPropertiesBoundPropertyStringSetBoundPropertyStringElement[] BoundPropertyStringElement {
            get {
                return this.boundPropertyStringElementField;
            }
            set {
                this.boundPropertyStringElementField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class BoundPropertiesBoundPropertyStringSetBoundPropertyStringElement {
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class BoundPropertiesBoundPropertyFloat {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class BoundPropertiesBoundPropertyInt {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class BoundPropertiesBoundPropertyString {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Transitions {
        
        private TransitionsShaderEffect[] shaderEffectField;
        
        private TransitionsShapeEffect[] shapeEffectField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ShaderEffect", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TransitionsShaderEffect[] ShaderEffect {
            get {
                return this.shaderEffectField;
            }
            set {
                this.shaderEffectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ShapeEffect", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TransitionsShapeEffect[] ShapeEffect {
            get {
                return this.shapeEffectField;
            }
            set {
                this.shapeEffectField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class TransitionsShaderEffect {
        
        private string boundPropertiesField;
        
        private string effectTemplateIDField;
        
        private string durationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BoundProperties {
            get {
                return this.boundPropertiesField;
            }
            set {
                this.boundPropertiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string effectTemplateID {
            get {
                return this.effectTemplateIDField;
            }
            set {
                this.effectTemplateIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string duration {
            get {
                return this.durationField;
            }
            set {
                this.durationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class TransitionsShapeEffect {
        
        private string boundPropertiesField;
        
        private string effectTemplateIDField;
        
        private string durationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BoundProperties {
            get {
                return this.boundPropertiesField;
            }
            set {
                this.boundPropertiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string effectTemplateID {
            get {
                return this.effectTemplateIDField;
            }
            set {
                this.effectTemplateIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string duration {
            get {
                return this.durationField;
            }
            set {
                this.durationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Project {
        
        private ProjectMediaItem[] mediaItemsField;
        
        private ProjectExtents extentsField;
        
        private ProjectBoundPlaceholder[] boundPlaceholdersField;
        
        private BoundProperties boundPropertiesField;
        
        private ProjectThemeOperationLog themeOperationLogField;
        
        private ProjectAudioDuckingProperties audioDuckingPropertiesField;
        
        private string nameField;
        
        private string themeIdField;
        
        private string versionField;
        
        private string templateIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("MediaItem", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ProjectMediaItem[] MediaItems {
            get {
                return this.mediaItemsField;
            }
            set {
                this.mediaItemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProjectExtents Extents {
            get {
                return this.extentsField;
            }
            set {
                this.extentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("BoundPlaceholder", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ProjectBoundPlaceholder[] BoundPlaceholders {
            get {
                return this.boundPlaceholdersField;
            }
            set {
                this.boundPlaceholdersField = value;
            }
        }
        
        /// <remarks/>
        public BoundProperties BoundProperties {
            get {
                return this.boundPropertiesField;
            }
            set {
                this.boundPropertiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProjectThemeOperationLog ThemeOperationLog {
            get {
                return this.themeOperationLogField;
            }
            set {
                this.themeOperationLogField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProjectAudioDuckingProperties AudioDuckingProperties {
            get {
                return this.audioDuckingPropertiesField;
            }
            set {
                this.audioDuckingPropertiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string themeId {
            get {
                return this.themeIdField;
            }
            set {
                this.themeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string templateID {
            get {
                return this.templateIDField;
            }
            set {
                this.templateIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ProjectMediaItem {
        
        private string idField;
        
        private string filePathField;
        
        private string arWidthField;
        
        private string arHeightField;
        
        private string durationField;
        
        private string songTitleField;
        
        private string songArtistField;
        
        private string songAlbumField;
        
        private string songCopyrightUrlField;
        
        private string songArtistUrlField;
        
        private string songAudioFileUrlField;
        
        private string stabilizationModeField;
        
        private string mediaItemTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string filePath {
            get {
                return this.filePathField;
            }
            set {
                this.filePathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string arWidth {
            get {
                return this.arWidthField;
            }
            set {
                this.arWidthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string arHeight {
            get {
                return this.arHeightField;
            }
            set {
                this.arHeightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string duration {
            get {
                return this.durationField;
            }
            set {
                this.durationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string songTitle {
            get {
                return this.songTitleField;
            }
            set {
                this.songTitleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string songArtist {
            get {
                return this.songArtistField;
            }
            set {
                this.songArtistField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string songAlbum {
            get {
                return this.songAlbumField;
            }
            set {
                this.songAlbumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string songCopyrightUrl {
            get {
                return this.songCopyrightUrlField;
            }
            set {
                this.songCopyrightUrlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string songArtistUrl {
            get {
                return this.songArtistUrlField;
            }
            set {
                this.songArtistUrlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string songAudioFileUrl {
            get {
                return this.songAudioFileUrlField;
            }
            set {
                this.songAudioFileUrlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string stabilizationMode {
            get {
                return this.stabilizationModeField;
            }
            set {
                this.stabilizationModeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string mediaItemType {
            get {
                return this.mediaItemTypeField;
            }
            set {
                this.mediaItemTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ProjectExtents {
        
        private ProjectExtentsTitleClip[] titleClipField;
        
        private ProjectExtentsVideoClip[] videoClipField;
        
        private ProjectExtentsImageClip[] imageClipField;
        
        private ProjectExtentsExtentSelector[] extentSelectorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TitleClip", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProjectExtentsTitleClip[] TitleClip {
            get {
                return this.titleClipField;
            }
            set {
                this.titleClipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("VideoClip", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProjectExtentsVideoClip[] VideoClip {
            get {
                return this.videoClipField;
            }
            set {
                this.videoClipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ImageClip", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProjectExtentsImageClip[] ImageClip {
            get {
                return this.imageClipField;
            }
            set {
                this.imageClipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ExtentSelector", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProjectExtentsExtentSelector[] ExtentSelector {
            get {
                return this.extentSelectorField;
            }
            set {
                this.extentSelectorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ProjectExtentsTitleClip {
        
        private string transitionsField;
        
        private ProjectExtentsTitleClipTextEffect[] effectsField;
        
        private BoundProperties boundPropertiesField;
        
        private string extentIDField;
        
        private string gapBeforeField;
        
        private string durationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Transitions {
            get {
                return this.transitionsField;
            }
            set {
                this.transitionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("TextEffect", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ProjectExtentsTitleClipTextEffect[] Effects {
            get {
                return this.effectsField;
            }
            set {
                this.effectsField = value;
            }
        }
        
        /// <remarks/>
        public BoundProperties BoundProperties {
            get {
                return this.boundPropertiesField;
            }
            set {
                this.boundPropertiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string extentID {
            get {
                return this.extentIDField;
            }
            set {
                this.extentIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string gapBefore {
            get {
                return this.gapBeforeField;
            }
            set {
                this.gapBeforeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string duration {
            get {
                return this.durationField;
            }
            set {
                this.durationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ProjectExtentsTitleClipTextEffect {
        
        private BoundProperties boundPropertiesField;
        
        private string effectTemplateIDField;
        
        private string textScriptIdField;
        
        /// <remarks/>
        public BoundProperties BoundProperties {
            get {
                return this.boundPropertiesField;
            }
            set {
                this.boundPropertiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string effectTemplateID {
            get {
                return this.effectTemplateIDField;
            }
            set {
                this.effectTemplateIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TextScriptId {
            get {
                return this.textScriptIdField;
            }
            set {
                this.textScriptIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ProjectExtentsVideoClip {
        
        private string effectsField;
        
        private Transitions transitionsField;
        
        private BoundProperties boundPropertiesField;
        
        private string extentIDField;
        
        private string gapBeforeField;
        
        private string mediaItemIDField;
        
        private string inTimeField;
        
        private string outTimeField;
        
        private string speedField;
        
        private string stabilizationModeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Effects {
            get {
                return this.effectsField;
            }
            set {
                this.effectsField = value;
            }
        }
        
        /// <remarks/>
        public Transitions Transitions {
            get {
                return this.transitionsField;
            }
            set {
                this.transitionsField = value;
            }
        }
        
        /// <remarks/>
        public BoundProperties BoundProperties {
            get {
                return this.boundPropertiesField;
            }
            set {
                this.boundPropertiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string extentID {
            get {
                return this.extentIDField;
            }
            set {
                this.extentIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string gapBefore {
            get {
                return this.gapBeforeField;
            }
            set {
                this.gapBeforeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string mediaItemID {
            get {
                return this.mediaItemIDField;
            }
            set {
                this.mediaItemIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string inTime {
            get {
                return this.inTimeField;
            }
            set {
                this.inTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string outTime {
            get {
                return this.outTimeField;
            }
            set {
                this.outTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string speed {
            get {
                return this.speedField;
            }
            set {
                this.speedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string stabilizationMode {
            get {
                return this.stabilizationModeField;
            }
            set {
                this.stabilizationModeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ProjectExtentsImageClip {
        
        private string effectsField;
        
        private Transitions transitionsField;
        
        private BoundProperties boundPropertiesField;
        
        private string extentIDField;
        
        private string gapBeforeField;
        
        private string mediaItemIDField;
        
        private string durationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Effects {
            get {
                return this.effectsField;
            }
            set {
                this.effectsField = value;
            }
        }
        
        /// <remarks/>
        public Transitions Transitions {
            get {
                return this.transitionsField;
            }
            set {
                this.transitionsField = value;
            }
        }
        
        /// <remarks/>
        public BoundProperties BoundProperties {
            get {
                return this.boundPropertiesField;
            }
            set {
                this.boundPropertiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string extentID {
            get {
                return this.extentIDField;
            }
            set {
                this.extentIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string gapBefore {
            get {
                return this.gapBeforeField;
            }
            set {
                this.gapBeforeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string mediaItemID {
            get {
                return this.mediaItemIDField;
            }
            set {
                this.mediaItemIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string duration {
            get {
                return this.durationField;
            }
            set {
                this.durationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ProjectExtentsExtentSelector {
        
        private string effectsField;
        
        private string transitionsField;
        
        private string boundPropertiesField;
        
        private ProjectExtentsExtentSelectorExtentRef[] extentRefsField;
        
        private string extentIDField;
        
        private string gapBeforeField;
        
        private string primaryTrackField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Effects {
            get {
                return this.effectsField;
            }
            set {
                this.effectsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Transitions {
            get {
                return this.transitionsField;
            }
            set {
                this.transitionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BoundProperties {
            get {
                return this.boundPropertiesField;
            }
            set {
                this.boundPropertiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ExtentRef", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ProjectExtentsExtentSelectorExtentRef[] ExtentRefs {
            get {
                return this.extentRefsField;
            }
            set {
                this.extentRefsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string extentID {
            get {
                return this.extentIDField;
            }
            set {
                this.extentIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string gapBefore {
            get {
                return this.gapBeforeField;
            }
            set {
                this.gapBeforeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string primaryTrack {
            get {
                return this.primaryTrackField;
            }
            set {
                this.primaryTrackField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ProjectExtentsExtentSelectorExtentRef {
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ProjectBoundPlaceholder {
        
        private string placeholderIDField;
        
        private string extentIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string placeholderID {
            get {
                return this.placeholderIDField;
            }
            set {
                this.placeholderIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string extentID {
            get {
                return this.extentIDField;
            }
            set {
                this.extentIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ProjectThemeOperationLog {
        
        private string monolithicThemeOperationsField;
        
        private string themeIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MonolithicThemeOperations {
            get {
                return this.monolithicThemeOperationsField;
            }
            set {
                this.monolithicThemeOperationsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string themeID {
            get {
                return this.themeIDField;
            }
            set {
                this.themeIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ProjectAudioDuckingProperties {
        
        private string emphasisPlaceholderIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string emphasisPlaceholderID {
            get {
                return this.emphasisPlaceholderIDField;
            }
            set {
                this.emphasisPlaceholderIDField = value;
            }
        }
    }
}
